spring.application.name=account

server.port=${PORT:8000}
server.address=0.0.0.0
client.service.url=${CLIENT_SERVICE_URL:http://localhost:8001/api/clients}

# Optimizacion de Pool de Conexiones HikariCP para Alta Concurrencia
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=2000