spring.application.name=client

server.port=${PORT:8001}
server.address=0.0.0.0

# Optimizacion de Pool de Conexiones HikariCP para Alta Concurrencia
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=2000

# Observabilidad de Produccion y Sondas de Kubernetes (Actuator)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true